server:
  port: 5000
 
jwt:
  secret: Key#SuperSecret$Aforo2SS#JavaMicroservices#987654321
 
spring:
  application:
    name: appgateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:      
      - id: appsecurity
        uri: http://localhost:80
        predicates:
          - Path=/security/**
        filters:
          - StripPrefix=1
      - id: appaccount
        uri: http://localhost:5002
        predicates:
          - Path=/account/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter          
      - id: appdeposit
        uri: http://localhost:5003
        predicates:
          - Path=/deposit/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter          
      - id: appwithdrawal
        uri: http://localhost:5004
        predicates:
          - Path=/withdrawal/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter          
      - id: appmovement
        uri: http://localhost:5005
        predicates:
          - Path=/movement/**
        filters:
          - StripPrefix=1
          - JwtAuthenticationFilter